# Generated by Django 5.0.1 on 2024-02-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_studentcourseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_student', to='main.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentcourseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='main.course'),
        ),
    ]
