# Generated by Django 5.0.1 on 2024-02-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studentcourseenrollment_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourseenrollment',
            old_name='student',
            new_name='student_id',
        ),
    ]
