# Generated by Django 5.0.1 on 2024-02-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_student_studentcourseenrollment_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourseenrollment',
            old_name='student_id',
            new_name='student',
        ),
    ]
