# Generated by Django 5.0.1 on 2024-03-06 11:18

import django.db.models.deletion
from django.db import migrations, models


# operations = [
#     migrations.RemoveField(
#         model_name='notification',
#         name='notif_text',
#     ),
#     migrations.DeleteModel(
#         name='Notification',
#     ),
#     migrations.AddField(
#         model_name='notification',
#         name='teacher',
#         field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
#         preserve_default=False,
#     ),
# ]



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_notification_options_and_more'),
    ]


    operations = [
    migrations.RemoveField(
        model_name='notification',
        name='notif_text',
    ),
    migrations.DeleteModel(
        name='Notification',
    ),
    migrations.AddField(
        model_name='notification',
        name='teacher',
        field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        preserve_default=False,
    ),
]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='notification',
    #         name='notif_text',
    #     ),
    #     migrations.AddField(
    #         model_name='notification',
    #         name='teacher',
    #         field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
    #         preserve_default=False,
    #     ),
    # ] youtube solution
